-- 
--  Copyright 2025; Réal Demers.
-- 
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
-- 
--  DDL for the staging database.
--  Simple database definition.

-- BEGIN.
--

-- DROP SECTION.
DROP TABLE IF EXISTS PUBLIC.REQUEST;
DROP TABLE IF EXISTS PUBLIC.INVENTORY;
DROP TABLE IF EXISTS PUBLIC.PRODUCT;
DROP TABLE IF EXISTS PUBLIC.PERSON;

--
-- Person table.
--
CREATE TABLE PUBLIC.PERSON (
	PERSON_ID  INTEGER               NOT NULL AUTO_INCREMENT,
	FIRST_NAME CHARACTER VARYING(64) NOT NULL,
	LAST_NAME  CHARACTER VARYING(64) NOT NULL,

	CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID)
);
CREATE UNIQUE INDEX PERSON_FIRST_LAST_NAME_IDX ON PUBLIC.PERSON (FIRST_NAME,LAST_NAME);

--
-- Product table.
--
CREATE TABLE PUBLIC.PRODUCT (
	PRODUCT_ID INTEGER                 NOT NULL AUTO_INCREMENT,
	CODE        CHARACTER VARYING(64)  NOT NULL,
	DESCRIPTION CHARACTER VARYING(128) NOT NULL,
	PRICE       REAL                   NOT NULL,
	
	CONSTRAINT PRODUCT_PK     PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT PRODUCT_UNIQUE UNIQUE (CODE)
);

--
-- Inventory table.
--
CREATE TABLE PUBLIC.INVENTORY (
	INVENTORY_ID INTEGER NOT NULL AUTO_INCREMENT,
	PRODUCT_ID   INTEGER NOT NULL,
	QTY 		 INTEGER NOT NULL,
	
	CONSTRAINT INVENTORY_PK         PRIMARY KEY (INVENTORY_ID),
	CONSTRAINT INVENTORY_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(PRODUCT_ID)
);
--
CREATE UNIQUE INDEX INVENTORY_INVENTORY_ID_IDX ON PUBLIC.INVENTORY (INVENTORY_ID, PRODUCT_ID);

--
-- Request table.
--
CREATE TABLE PUBLIC.REQUEST (
	REQUEST_ID 	INTEGER NOT NULL AUTO_INCREMENT,
	PERSON_ID 	INTEGER NOT NULL,
	ACTION 		INTEGER NOT NULL,
	PRODUCT_ID 	INTEGER NOT NULL,
	QTY 		INTEGER NOT NULL,
	STATUS 		INTEGER NOT NULL,
	
	CONSTRAINT REQUEST_PK         PRIMARY KEY (REQUEST_ID),
	CONSTRAINT REQUEST_PERSON_FK  FOREIGN KEY (PERSON_ID)  REFERENCES PUBLIC.PERSON(PERSON_ID) 
	                              ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT REQUEST_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(PRODUCT_ID)
	                              ON DELETE RESTRICT ON UPDATE RESTRICT
);
--
-- END.