-- 
--  Copyright 2026; Réal Demers.
-- 
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
-- 
--  DDL for the staging database.
--  Simple database definition.

-- BEGIN.
--
-- Force the concurrency model on every startup (a file DB persists this setting in its
-- .properties, so the hsqldb.tx URL property is only honored at first creation).
-- MVCC (not mvlocks): empirically verified to let concurrent blind relative UPDATEs
-- (e.g. InventoryRepository.creditQTY) apply without any conflict/lock being raised,
-- which is what actually reproduces the inventory oversell race this sandbox teaches.
SET DATABASE TRANSACTION CONTROL MVCC;

DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS JRN_EVENT;

CREATE TABLE PERSON (
    VERSION    INTEGER DEFAULT 0 NOT NULL,
    PERSON_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME VARCHAR(64)    NOT NULL,
    LAST_NAME  VARCHAR(64)    NOT NULL,
    BALANCE    DECIMAL(10, 2) NOT NULL,

    CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID),
    CONSTRAINT PERSON_FIRST_LAST_NAME_UK UNIQUE (FIRST_NAME, LAST_NAME)
);

CREATE TABLE PRODUCT (
    VERSION     INTEGER DEFAULT 0 NOT NULL,
    PRODUCT_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CODE        VARCHAR(64)    NOT NULL,
    DESCRIPTION VARCHAR(128)   NOT NULL,
    PRICE       DECIMAL(10, 2) NOT NULL,

    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT PRODUCT_CODE_UK UNIQUE (CODE)
);

CREATE TABLE INVENTORY (
    VERSION      INTEGER DEFAULT 0 NOT NULL,
    INVENTORY_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PRODUCT_ID   INTEGER NOT NULL,
    QTY          INTEGER NOT NULL,

    CONSTRAINT INVENTORY_PK PRIMARY KEY (INVENTORY_ID),
    CONSTRAINT INVENTORY_PRODUCT_UK UNIQUE (PRODUCT_ID),
    CONSTRAINT INVENTORY_PRODUCT_FK FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE REQUEST (
    VERSION     INTEGER DEFAULT 0 NOT NULL,
    REQUEST_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PERSON_ID   INTEGER NOT NULL,
    PRODUCT_ID  INTEGER NOT NULL,
    QTY         INTEGER NOT NULL,
    OPERATION   INTEGER NOT NULL,
    RESULT      INTEGER NOT NULL,


    CONSTRAINT REQUEST_PK PRIMARY KEY (REQUEST_ID),
    CONSTRAINT REQUEST_PERSON_FK FOREIGN KEY (PERSON_ID)
               REFERENCES PERSON (PERSON_ID) ON DELETE RESTRICT,
    CONSTRAINT REQUEST_PRODUCT_FK FOREIGN KEY (PRODUCT_ID)
               REFERENCES PRODUCT (PRODUCT_ID) ON DELETE RESTRICT
);
--
CREATE TABLE JRN_EVENT (
    VERSION      INTEGER DEFAULT 0 NOT NULL,
    JRN_EVENT_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CONSUMER_ID  VARCHAR(64)  NOT NULL, -- The consumer ID is the name of the consumer group that received the event.
    EVENT_ID     VARCHAR(64)  NOT NULL,
    BATCH_ID     VARCHAR(64)  NOT NULL,
    PAYLOAD_HASH VARCHAR(64)  NOT NULL,
    EVENT_TYPE   INTEGER      NOT NULL,
    RESULT       INTEGER      NOT NULL,
    RECEIVED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESSED_AT TIMESTAMP,

    CONSTRAINT JRN_EVENT_PK PRIMARY KEY (JRN_EVENT_ID),
    CONSTRAINT JRN_EVENT_UNIQUE_CONSUMER_EVENT UNIQUE (CONSUMER_ID, EVENT_ID),
    CONSTRAINT JRN_EVENT_UNIQUE_BATCH_HASH UNIQUE (CONSUMER_ID, EVENT_ID, BATCH_ID, PAYLOAD_HASH)
);
--
-- END.