CREATE TABLE PUBLIC.PRODUCT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CODE_KEY CHARACTER(32) NOT NULL,
	UUID_KEY UUID NOT NULL,
	CONSTRAINT PRODUCT_PK PRIMARY KEY (ID),
	CONSTRAINT PRODUCT_UNIQUE_CODE UNIQUE (CODE),
	CONSTRAINT PRODUCT_UNIQUE_UUID UNIQUE (UUID_KEY)
);
