/*
 * Copyright 2026; Réal Demers.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.rd.fullstack.springbooteda.util.kafka;

import java.util.Collections;
import java.util.Map;
import java.util.Set;

import org.apache.kafka.clients.admin.NewTopic;
import org.apache.kafka.common.Metric;
import org.apache.kafka.common.MetricName;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.test.EmbeddedKafkaKraftBroker;

import kafka.server.BrokerServer;

/**
 * {@link BrokerLifecycle} implementation backed by a Spring-Kafka
 * {@link EmbeddedKafkaKraftBroker} (in-process, KRaft mode).
 * <p>
 * This is the default implementation used when no external bootstrap-servers
 * URL is provided to {@link KafkaSandbox.Builder}.  It is ideal for local
 * development and integration tests because no external Kafka infrastructure
 * is required.
 * <p>
 * <b>Note on internal API usage:</b> {@link #getBrokerMetrics()} relies on
 * the Kafka internal class {@code kafka.server.BrokerServer}.  This API is
 * not guaranteed to be stable across Kafka versions.
 * <p>
 * Package-private: not part of the public API of this library.
 */
class EmbeddedBrokerLifecycle implements BrokerLifecycle {

    private static final Logger logger =
            LoggerFactory.getLogger(EmbeddedBrokerLifecycle.class);

    // volatile: written once in start(), then read (never updated) until stop().
    private volatile EmbeddedKafkaKraftBroker kBroker;

    @Override
    public void start(KafkaConfig cfg, Map<String, TopicConfig> topicRegistry) {
        EmbeddedKafkaKraftBroker broker =
                new EmbeddedKafkaKraftBroker(cfg.clusters(), cfg.clusterPartitions());
        broker.brokerProperties(buildBrokerProperties(cfg));
        broker.afterPropertiesSet();
        kBroker = broker;

        if (!topicRegistry.isEmpty()) {
            topicRegistry.values().forEach(this::syncTopic);
            logger.info("Topics created on embedded broker: {}.", topicRegistry.keySet());
        }
    }

    @Override
    public void stop() {
        EmbeddedKafkaKraftBroker broker = kBroker;
        kBroker = null;
        if (broker != null) {
            try {
                broker.destroy();
            } catch (Exception ex) {
                logger.warn("Exception destroying embedded Kafka broker: {}.", ex.getMessage());
            }
        }
    }

    @Override
    public String getBootstrapServers() {
        return requireBroker().getBrokersAsString();
    }

    @Override
    public boolean isStarted() {
        return kBroker != null;
    }

    @Override
    public Set<String> getTopics() {
        return requireBroker().getTopics();
    }

    @Override
    public void syncTopic(TopicConfig topicConfig) {
        EmbeddedKafkaKraftBroker broker = requireBroker();

        // Possibly a duplicate — DLT topic entries may cause a form of duplication.
        if (broker.getTopics().contains(topicConfig.name()))
            return;

        broker.addTopics(
            new NewTopic(topicConfig.name(), topicConfig.partitions(), topicConfig.replicas()));

        // Specific DLT — Dead Letter Topic?
        if (!topicConfig.dltName().isEmpty()) {
            // Possibly a duplicate — DLT topic entries may cause a form of duplication.
            if (broker.getTopics().contains(topicConfig.dltName()))
                return;

            broker.addTopics(
                new NewTopic(topicConfig.dltName(), topicConfig.partitions(), topicConfig.replicas()));
        }
    }

    /**
     * Returns broker-level metrics via the internal {@code kafka.server.BrokerServer} API.
     *
     * @throws IllegalStateException     if the broker has not been started
     * @throws UnsupportedOperationException if no broker servers are present
     */
    @Override
    public Map<MetricName, ? extends Metric> getBrokerMetrics() {
        EmbeddedKafkaKraftBroker broker = requireBroker();
        Map<Integer, BrokerServer> brokers = broker.getCluster().brokers();
        if (brokers.isEmpty())
            return Collections.emptyMap();

        return brokers.values().iterator().next().metrics().metrics();
    }

    private Map<String, String> buildBrokerProperties(KafkaConfig cfg) {
        return Map.of(
            // "cluster.id" is auto-generated by EmbeddedKafkaKraftBroker — do not set.
            "auto.create.topics.enable",                  String.valueOf(cfg.autoCreateTopic()),
            "log.retention.hours",                        "1",
            "transaction.state.log.replication.factor",   "1",
            "transaction.state.log.min.isr",              "1",
            "offsets.topic.replication.factor",           "1"
        );
    }

    private EmbeddedKafkaKraftBroker requireBroker() {
        EmbeddedKafkaKraftBroker broker = kBroker; // Single volatile read.
        if (broker == null)
            throw new IllegalStateException("EmbeddedBrokerLifecycle is not started.");
        return broker;
    }
}
